In [9]:
from numpy import matrix
import numpy as np
count = 1
for x in range(0,100):
    if count == 1:
        X = 0.1
        Y = 1
    f1 = X*X - 10*X + Y*Y - 10*Y + 34
    f2 = X*X - 22*X + Y*Y - 10*Y + 130
    if f1 == 0 and f2==0:
        break
    print ("\r\nIteration=%d" %count)
    count += 1
    print ("f1= %f" %(f1))
    print ("f2=%f" %(f2))
    
    A = 2*X - 10
    B = 2*Y - 10
    C = 2*X - 22
    D = 2*Y - 10
    print (A,B)
    print (C,D)
    J = np.matrix([[A,B],[C,D]]).I
    f3 = np.matrix([[f1],[f2]])
    T = np.matrix([[X],[Y]])
    Delta = J*f3
    E = T-Delta
    X = np.squeeze(np.asarray(E[0]))
    Y = np.squeeze(np.asarray(E[1]))
    print (J)
    print ("X=%f, Y=%f" %(X,Y))


Iteration=1
f1= 24.010000
f2=118.810000
-9.8 -8
-21.8 -8
[[ 0.08333333 -0.08333333]
 [-0.22708333  0.10208333]]
X=8.000000, Y=-5.676250

Iteration=2
f1= 106.982314
f2=106.982314
6.0 -21.3525
-6.0 -21.3525
[[ 0.08333333 -0.08333333]
 [-0.02341646 -0.02341646]]
X=8.000000, Y=-0.665955

Iteration=3
f1= 25.103051
f2=25.103051
6.0 -11.331910929633532
-6.0 -11.331910929633532
[[ 0.08333333 -0.08333333]
 [-0.04412318 -0.04412318]]
X=8.000000, Y=1.549298

Iteration=4
f1= 4.907346
f2=4.907346
6.0 -6.90140463900585
-6.0 -6.90140463900585
[[ 0.08333333 -0.08333333]
 [-0.07244902 -0.07244902]]
X=8.000000, Y=2.260363

Iteration=5
f1= 0.505613
f2=0.505613
6.0 -5.479274868469812
-6.0 -5.479274868469812
[[ 0.08333333 -0.08333333]
 [-0.09125295 -0.09125295]]
X=8.000000, Y=2.352640

Iteration=6
f1= 0.008515
f2=0.008515
5.999999999999998 -5.294720056675011
-6.000000000000002 -5.294720056675011
[[ 0.08333333 -0.08333333]
 [-0.0944337  -0.0944337 ]]
X=8.000000, Y=2.354248

Iteration=7
f1= 0.000003
f2=0.00